name: e2e
on:
  pull_request_review:
    branches:
      - master
    types: [submitted]
  push:
    branches-ignore:
      - master
concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    if: >-
      github.event_name == 'schedule' ||
      (github.event_name == 'push' &&
      !contains(github.event.head_commit.message, 'chore: update dist folder')) ||
      (github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5, 6, 7, 8]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
      - uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-e2e
          restore-keys: |
            ${{ runner.os }}-node-e2e
      - run: npm ci
        env:
          # https://playwright.dev/docs/installation/#skip-browser-downloads
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npm run build
      - run: npx playwright install-deps
      - run: npx playwright install
      - run: npm run test:playwright -- --shard=${{matrix.shard}}/8
        env:
          CI: true
      - name: Push test report to artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Test Results
          path: test-results/
