name: Publish to demo.woosmap.com
on:
  push:
    branches:
      - master
jobs:
  push-to-s3:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
      - run: npm ci
      - run: npm run build
      - name: include ignored files
        run: |
          rm -rf dist/samples/**/node_modules
          rm -rf dist/samples/**/package-lock.json
          rm -rf dist/samples/**/app/.gitignore
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync dist s3://demo.woosmap.com/js-samples/ --acl public-read
